<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.YwRB2Jv' shared service.

return $this->privates['.service_locator.YwRB2Jv'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['article' => function (): \App\Entity\Article {
    return ($this->privates['.errored..service_locator.YwRB2Jv.App\Entity\Article'] ?? $this->load('getArticle2Service.php'));
}, 'slack' => function (): \App\Service\SlackClient {
    return ($this->privates['App\Service\SlackClient'] ?? $this->load('getSlackClientService.php'));
}]);
