<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Security\Voter\ArticleVoter' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Authorization/Voter/VoterInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Authorization/Voter/Voter.php';
include_once $this->targetDirs[3].'/src/Security/Voter/ArticleVoter.php';

return $this->privates['App\Security\Voter\ArticleVoter'] = new \App\Security\Voter\ArticleVoter(($this->privates['security.helper'] ?? $this->load('getSecurity_HelperService.php')));
