<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.N4f9btw.App\Entity\Article' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.N4f9btw": it references class "App\\Entity\\Article" but no such service exists.');
