<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cJHlmkK' shared service.

return $this->privates['.service_locator.cJHlmkK'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['encoder' => function () {
    return ($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php'));
}, 'gardHandler' => function () {
    return ($this->privates['security.authentication.guard_handler'] ?? $this->load('getSecurity_Authentication_GuardHandlerService.php'));
}, 'loginFormAuthenticator' => function (): \App\Security\LoginFormAuthenticator {
    return ($this->privates['App\Security\LoginFormAuthenticator'] ?? $this->load('getLoginFormAuthenticatorService.php'));
}]);
