<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.N4f9btw' shared service.

return $this->privates['.service_locator.N4f9btw'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['article' => function (): \App\Entity\Article {
    return ($this->privates['.errored..service_locator.N4f9btw.App\Entity\Article'] ?? $this->load('getArticleService.php'));
}, 'em' => function () {
    return ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));
}, 'logger' => function () {
    return ($this->privates['monolog.logger'] ?? $this->load('getMonolog_LoggerService.php'));
}]);
