<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['App\\Controller\\ArticleAdminController::new' => function () {
    return ($this->privates['.service_locator.v_q6gfB'] ?? $this->load('get_ServiceLocator_VQ6gfBService.php'));
}, 'App\\Controller\\ArticleController::homepage' => function () {
    return ($this->privates['.service_locator.Mc5zpHk'] ?? $this->load('get_ServiceLocator_Mc5zpHkService.php'));
}, 'App\\Controller\\ArticleController::show' => function () {
    return ($this->privates['.service_locator.YwRB2Jv'] ?? $this->load('get_ServiceLocator_YwRB2JvService.php'));
}, 'App\\Controller\\ArticleController::toggleArticleHeart' => function () {
    return ($this->privates['.service_locator.N4f9btw'] ?? $this->load('get_ServiceLocator_N4f9btwService.php'));
}, 'App\\Controller\\CommentAdminController::index' => function () {
    return ($this->privates['.service_locator.aVICUrH'] ?? $this->load('get_ServiceLocator_AVICUrHService.php'));
}, 'App\\Controller\\ArticleAdminController:new' => function () {
    return ($this->privates['.service_locator.v_q6gfB'] ?? $this->load('get_ServiceLocator_VQ6gfBService.php'));
}, 'App\\Controller\\ArticleController:homepage' => function () {
    return ($this->privates['.service_locator.Mc5zpHk'] ?? $this->load('get_ServiceLocator_Mc5zpHkService.php'));
}, 'App\\Controller\\ArticleController:show' => function () {
    return ($this->privates['.service_locator.YwRB2Jv'] ?? $this->load('get_ServiceLocator_YwRB2JvService.php'));
}, 'App\\Controller\\ArticleController:toggleArticleHeart' => function () {
    return ($this->privates['.service_locator.N4f9btw'] ?? $this->load('get_ServiceLocator_N4f9btwService.php'));
}, 'App\\Controller\\CommentAdminController:index' => function () {
    return ($this->privates['.service_locator.aVICUrH'] ?? $this->load('get_ServiceLocator_AVICUrHService.php'));
}])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
