<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMG9G4Fx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMG9G4Fx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMG9G4Fx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMG9G4Fx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMG9G4Fx\srcDevDebugProjectContainer([
    'container.build_hash' => 'MG9G4Fx',
    'container.build_id' => 'fefdf591',
    'container.build_time' => 1611690587,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMG9G4Fx');
