<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIlBjBAN\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIlBjBAN/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIlBjBAN.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIlBjBAN\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIlBjBAN\srcDevDebugProjectContainer([
    'container.build_hash' => 'IlBjBAN',
    'container.build_id' => '7c18bff8',
    'container.build_time' => 1611577784,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIlBjBAN');
