<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF9KvPhY\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF9KvPhY/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerF9KvPhY.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerF9KvPhY\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerF9KvPhY\srcDevDebugProjectContainer([
    'container.build_hash' => 'F9KvPhY',
    'container.build_id' => '0ce804db',
    'container.build_time' => 1610887778,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF9KvPhY');
